packages:
  - packages/*
catalog:
catalogs:
  build:
    '@nuxt/kit': ^4.0.1
    '@unocss/nuxt': ^66.3.3
    '@vueuse/nuxt': ^13.5.0
    esbuild: ^0.25.8
    nitropack: ^2.12.3
    nuxt: ^4.0.1
    nuxt-mcp: ^0.2.3
    rolldown: https://pkg.pr.new/rolldown@2502d39
    tsdown: ^0.13.0
    tsx: ^4.20.3
    vite: npm:rolldown-vite@^7.0.9
  deps:
    '@rolldown/debug': https://pkg.pr.new/@rolldown/debug@2502d39
    ansis: ^4.1.0
    birpc: ^2.5.0
    cac: ^6.7.14
    diff: ^8.0.2
    get-port-please: ^3.2.0
    h3: ^1.15.3
    launch-editor: ^2.10.0
    mlly: ^1.7.4
    mrmime: ^2.0.1
    ohash: ^2.0.11
    open: ^10.2.0
    p-limit: ^6.2.0
    pathe: ^2.0.3
    publint: ^0.3.12
    structured-clone-es: ^1.0.0
    tinyglobby: ^0.2.14
    unconfig: ^7.3.2
    unstorage: ^1.16.1
    webext-bridge: ^6.0.1
    ws: ^8.18.3
  devtools:
    '@antfu/eslint-config': ^4.17.0
    '@nuxt/devtools': ^2.6.2
    '@nuxt/eslint': ^1.7.0
    '@typescript-eslint/utils': ^8.38.0
    '@unocss/eslint-config': ^66.3.3
    bumpp: ^10.2.0
    eslint: ^9.31.0
    lint-staged: ^16.1.2
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.13.0
    typescript: ^5.8.3
    vite-plugin-inspect: ^11.3.0
    vue-tsc: ^3.0.3
  frontend:
    '@vueuse/components': ^13.5.0
    '@vueuse/router': ^13.5.0
    codemirror: ^5.65.19
    codemirror-theme-vars: ^0.1.2
    comlink: ^4.4.2
    d3: ^7.9.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    diff-match-patch-es: ^1.0.1
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    idb-keyval: ^6.2.2
    nanovis: ^0.1.3
    splitpanes: ^4.0.4
    theme-vitesse: ^0.8.3
    vite-hot-client: ^2.1.0
    vue: ^3.5.17
  icons:
    '@iconify-json/carbon': ^1.2.11
    '@iconify-json/catppuccin': ^1.2.11
    '@iconify-json/codicon': ^1.2.24
    '@iconify-json/logos': ^1.2.4
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/simple-icons': ^1.2.44
    '@iconify-json/svg-spinners': ^1.2.2
  inlined:
    '@antfu/utils': ^9.2.0
    stream-json: ^1.9.1
  testing:
    vitest: ^3.2.4
  types:
    '@types/chrome': ^0.1.1
    '@types/codemirror': ^5.60.16
    '@types/connect': ^3.4.38
    '@types/d3': ^7.4.3
    '@types/d3-hierarchy': ^3.1.7
    '@types/diff': ^8.0.0
    '@types/stream-json': ^1.7.8
    '@types/ws': ^8.18.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - simple-git-hooks
  - unrs-resolver
